### ISSUE TITLE
Conflict with upgrade status module (on drupal 9.x)

### ISSUE THREAD

**Issue by BramG** [Nascom/grumphp-drupal#1]
Problem 1
    - Conclusion: don't install drupal/upgrade_status 3.13.0 (conflict analysis result)
    - Conclusion: don't install mglaman/phpstan-drupal 0.12.10 (conflict analysis result)
    - drupal/core-dev is locked to version 9.3.0 and an update of this package was not requested.
    - phpstan/phpstan-deprecation-rules 1.0.x-dev is an alias of phpstan/phpstan-deprecation-rules dev-master and thus requires it to be installed too.
    - mglaman/phpstan-drupal 0.11.14 conflicts with phpstan/phpstan-deprecation-rules 1.0.x-dev.
    - drupal/upgrade_status dev-3.x requires phpstan/phpstan-deprecation-rules ^1.0.0 -> satisfiable by phpstan/phpstan-deprecation-rules[1.0.0, 1.0.x-dev (alias of dev-master)].
    - Conclusion: don't install phpstan/phpstan-deprecation-rules 1.0.0 (conflict analysis result)
    - Conclusion: don't install composer/xdebug-handler[2.0.3] | install one of mglaman/phpstan-drupal[0.12.0, ..., 0.12.10] (conflict analysis result)
    - Conclusion: don't install mglaman/phpstan-drupal 0.12.0 (conflict analysis result)
    - Conclusion: don't install mglaman/phpstan-drupal 0.12.1 (conflict analysis result)
    - Conclusion: don't install mglaman/phpstan-drupal 0.12.2 (conflict analysis result)
    - Conclusion: don't install mglaman/phpstan-drupal 0.12.3 (conflict analysis result)
    - Conclusion: don't install mglaman/phpstan-drupal 0.12.4 (conflict analysis result)
    - Conclusion: don't install mglaman/phpstan-drupal 0.12.5 (conflict analysis result)
    - Conclusion: don't install mglaman/phpstan-drupal 0.12.6 (conflict analysis result)
    - Conclusion: don't install mglaman/phpstan-drupal 0.12.7 (conflict analysis result)
    - Conclusion: don't install mglaman/phpstan-drupal 0.12.8 (conflict analysis result)
    - Conclusion: don't install mglaman/phpstan-drupal 0.12.9 (conflict analysis result)
    - drupal/upgrade_status 3.x-dev is an alias of drupal/upgrade_status dev-3.x and thus requires it to be installed too.
    - nascom/grumphp-drupal is locked to version 1.0.0 and an update of this package was not requested.
    - Root composer.json requires drupal/upgrade_status ^3.13 -> satisfiable by drupal/upgrade_status[3.13.0, 3.x-dev (alias of dev-3.x)].
    - phpstan/phpstan 1.3.x-dev is an alias of phpstan/phpstan dev-master and thus requires it to be installed too.
    - You can only install one version of a package, so only one of these can be installed: phpstan/phpstan[dev-master, 0.1, ..., 0.12.x-dev, 1.0.0, ..., 1.2.0].
    - phpstan/phpstan-deprecation-rules dev-master requires phpstan/phpstan ^1.3 -> satisfiable by phpstan/phpstan[1.3.x-dev (alias of dev-master)].
    - Conclusion: install one of mglaman/phpstan-drupal[0.11.14, ..., 0.12.9], phpstan/phpstan[0.10.9], composer/xdebug-handler[2.0.3] (conflict analysis result)

You can also try re-running composer require with an explicit version constraint, e.g. "composer require drupal/upgrade_status:*" to figure out if any version is installable, or "composer require drupal/upgrade_status:^2.1" if you know which you need.

=> Why is this package locked on a phpstan version < 1?
=> Do we need a new branch to support drupal 9?

**Comment by mark-gerarts** [comment]
Resolved in 284d278 (1.1.0), phpstan(-drupal) dependencies were outdated.
